name: Ship

on:
  push:
    branches: [master]


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2

      - name: Publish eggs
        run: |
          deno run -A --unstable mod.ts link ${{ secrets.NESTAPIKEY }}
          deno run -A --unstable mod.ts publish

      - name: Draft release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-template.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
