name: Ship

on:
  push:
    branches: [master]


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2

      - name: Draft release
        id: draft_release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-template.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish eggs
        # TODO(@oganexon): remove --description after next release
        run: |
          deno run -A --unstable mod.ts link ${{ secrets.NESTAPIKEY }}
          deno run -A --unstable mod.ts publish eggs --ignore "extends .gitignore" --version ${{ steps.draft_release.outputs.tag_name }} --description "The CLI used to publish and update modules in nest.land.

