name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: "0 9 * * *"

jobs:
  stable:
    name: Deno Stable

    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2

      - name: Run tests
        run: deno test -A --unstable
      
      - name: Eggs release test
        run: |
          deno run -A --unstable mod.ts link ${{ secrets.NESTAPIKEY }}
          deno run -A --unstable mod.ts publish eggs --dry-run --ignore "extends .gitignore"

  nightly:
    name: Deno Nightly

    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: nightly

      - name: Run tests
        run: deno test -A --unstable
