name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: "0 9 * * *"

jobs:
  stable:
    name: Deno Stable

    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2

      - name: Run tests
        run: deno test -A --unstable

      - name: Get eggs version
        run: |
          deno run ./src/version/printVersion.ts
          echo "::set-env name=EGGS_VERSION::$(deno run ./src/version/printVersion.ts)"

      - name: Eggs release test
        run: |
          deno run -A --unstable mod.ts link ${{ secrets.NESTAPIKEY || "null" }} -do
          deno run -A --unstable mod.ts publish eggs --dry-run -do --ignore "extends .gitignore" --version ${{ env.EGGS_VERSION }}
        
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: eggs-debug
          path: eggs-debug.log

  nightly:
    name: Deno Nightly

    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: nightly

      - name: Run tests
        run: deno test -A --unstable

      - name: Get eggs version
        run: |
          deno run ./src/version/printVersion.ts
          echo "::set-env name=EGGS_VERSION::$(deno run ./src/version/printVersion.ts)"

      - name: Eggs release test
        run: |
          deno run -A --unstable mod.ts link ${{ secrets.NESTAPIKEY || "null" }} -do
          deno run -A --unstable mod.ts publish eggs --dry-run -do --ignore "extends .gitignore" --version ${{ env.EGGS_VERSION }}
      
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: eggs-debug
          path: eggs-debug.log
