name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: '0 9 * * *'

jobs:
  stable:
    name: Deno Stable

    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]

    env:
      NESTAPIKEY: ${{ secrets.NESTAPIKEY }}

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: maximousblk/setup-deno@v1

      - name: Setup Drake
        run: deno run -A --unstable Drakefile.ts setup-github-actions

      - name: Run tests
        run: drake test

      - name: Eggs release test
        run: drake dry-ship

      - name: Upload debug file
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: eggs-debug
          path: eggs-debug.log

  canary:
    name: Deno Canary

    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: maximousblk/setup-deno@v1
        with:
          deno-version: canary

      - name: Setup Drake
        run: deno run -A --unstable Drakefile.ts setup-github-actions

      - name: Run tests
        run: drake test

      - name: Eggs release test
        run: drake dry-ship

      - name: Upload debug file
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: eggs-debug
          path: eggs-debug.log
